config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#welcome'

  devise_for :users

  resources :users, :only => [:show]

  resources :products do
    resources :reviews, :except => [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :price, :presence => true

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  has_many :reviews
  has_many :users, through: :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products, through: :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)
      products_path
    else
      super
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :except => [:index, :show] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    if @product = Product.create!(product_params)
      redirect_to products_path, notice: 'Product successfully added'
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product), notice: 'Product successfully updated'
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.reviews.each do |review|
      review.destroy
    end
    @product.destroy
    redirect_to products_path, notice: 'Product successfully removed'
  end

private

  def product_params
    params.require(:product).permit(:name, :description, :price, :picture)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_product
  before_action do
    redirect_to new_user_session_path unless current_user
  end

  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @review = @product.reviews.new(content: review_params[:content], rating: review_params[:rating], user_id: params[:user_id])
    if @review.save
      redirect_to product_path(@product), notice: 'Successfully added review'
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@product), notice: 'Successfully edited review'
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product), notice: 'Successfully deleted review'
  end

private

  def review_params
    params.require(:review).permit(:content, :rating, :user_id)
  end

  def find_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id='errors' class='container card'>
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craftsy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">Craftsy</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/products">Marketplace</a>
          </li>
        </ul>

        <ul class="navbar-nav">
          <% if !current_user %>
          <li>
            <a class="nav-link" href="/users/sign_up">Register</a>
          </li>
          <li>
            <a class="nav-link" href="/users/sign_in">Sign In</a>
          </li>
          <% else %>
          <li>
            <a class="nav-link" href="/users/<%= current_user.id %>"><%= current_user.email %></a>
          </li>
          <li>
            <a class="nav-link" href="/users/sign_out" data-method='delete'>Sign Out</a>
          </li>
          <% end %>
        </ul>

        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <div class='container-fluid'>

      <div id='flash'>
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>

      <%= yield %>

    </div>

    <% if current_user && current_user.admin %>
      <footer class="footer">
        <div class="container text-right">
          <h4>Admin</h4>
          <%= link_to "Add New Product", new_product_path %>
        </div>
      </footer>
    <% end %>

  </body>
</html>

app/views/products/_form.html.erb
<%= render 'layouts/errors', :object => @product %>

<%= form_for @product, html: { multipart: true } do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <br>
    <%= f.text_field :description %>
  </div>
  <div class='form-group'>
    <%= f.label :price %>
    <br>
    <%= f.text_field :price %>
  </div>
  <div class='form-group'>
    <%= f.label :picture %>
    <br>
    <%= f.file_field :picture %>
  </div>
  <%= f.submit :class => 'btn btn-outline-success'%>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product Details</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Craftsy Marketplace</h1>

<div class='row'>
  <% @products.each do |product| %>
    <div class='col-md-4'>
      <div class='card'>
        <a href='/products/<%= product.id %>'><%= image_tag product.picture.url, :class => 'card-img-top', :alt => 'product image' %></a>
        <div class="card-block">
          <h4 class="card-title"><%= link_to product.name, product_path(product) %></h4>
          <p class="card-text"><%= product.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>Add a New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%= number_to_currency @product.price %></h3>

<%= image_tag @product.picture.url, :alt => 'product image' %>
<h4><%= @product.description %></h4>

<% if current_user && current_user.admin %>
  <%= link_to 'Edit product details', edit_product_path(@product), :class => 'btn btn-outline-info' %>
  <br>
  <%= link_to 'Remove product', product_path(@product), :method => 'delete', :data => { :confirm => 'Are you sure you want to remove this product?' }, :class => 'btn btn-outline-danger' %>
<% end %>

<hr>

<h3>Customer Reviews</h3>

<%= link_to 'Add a Review', new_product_review_path(@product), :class => 'btn btn-outline-primary' %>

<br><br>

<ul>
  <% @product.reviews.each do |review| %>
    <% user = User.find(review.user_id) %>
    <li><%= user.email %>, <%= review.rating %>/5</li>
      <ul>
        <li><%= review.content %></li>
        <% if current_user && review.user_id == current_user.id %>
        <li>
          <%= link_to 'Edit', edit_product_review_path(@product, review), :class => 'btn btn-outline-info btn-sm' %>
          <%= link_to 'Delete', product_review_path(@product, review), :method => 'delete', :data => { :confirm => 'Are you sure you want to delete this review?' }, :class => 'btn btn-outline-danger btn-sm' %>
        </li>
        <% end %>
      </ul>
  <% end %>
</ul>

app/views/reviews/_form.html.erb
<%= render 'layouts/errors', :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <div class='form-group'>
    <%= f.label :content %>
    <br>
    <%= f.text_field :content %>
  </div>
  <div class='form-group'>
    <%= f.label :rating %>
    <br>
    <%= f.text_field :rating %>
  </div>
  <input type='hidden' name='user_id' value='<%= current_user.id %>'>
  <%= f.submit :class => 'btn btn-outline-success'%>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review for <%= @product.name %></h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>Leave a Review for <%= @product.name %></h1>

<%= render 'form' %>

app/views/users/welcome.html.erb
<h1 id='welcome-title'>Craftsy</h1>

<div class='card' id='welcome-tagline'>
  <h3>Craftsy is an online commerce platform for creative entrepreneurs to display their unique goods.</h3>
</div>